### PR TITLE
SUPER fix for the SUPER issue!

### LINKED ISSUE #4: SUPER issue
Super image:
Alt-Text

### PR DESCRIPTION
**Pull request by dschoenicke**
This contains three complex model classes and an enhanced WelcomeController.

Fixes #4

### CODE REVIEW

File: src/main/java/stroempebukser/model/Fax.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ * 
+ * @author dschoenicke
+ *
+ */
+public class Fax {
+	
+	private String problem;
+	
+	public Fax(String problem) {
+		this.problem = problem;
```
Comment (prosenkranz) [inline src/main/java/stroempebukser/model/Fax.java]: Welp, unfortunately i doubt we can just assign problems like this :(

File: src/main/java/com/example/WelcomeController.java [hunk 2]
```diff
@@ -17,8 +18,9 @@
 public class WelcomeController {
 	
 	@RequestMapping("/")
-	public String index(Model model) {
-		model.addAttribute("name", "Tony");
-		return "index"; // this is the name of the JSP?
+	public ModelAndView index(Model model) {
+		String projectUrl = "https://raw.githubusercontent.com/prosenkranz/stroempebukser/nicebranch/verysuper.jpg";
+
```
Comment (prosenkranz) [inline src/main/java/com/example/WelcomeController.java]: Dood wot m8???? Dhis line is 100% not necessary ya dipshit, c'mon man. Remove dhis shit

**Comment by prosenkranz** [comment]
WOAH GEIL

Super!

Excellent

Good job

Keep going!

lgtm btw
